services:
  - type: web
    name: retalla
    env: node
    plan: free
    buildCommand: npm install --prefix server && npm install --include=dev --prefix web && npm run build --prefix web
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NODE_VERSION
        value: 22.12.0
      - key: ADMIN_NAME
        value: Retalla Admin
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
